# Header
menu:
  Home: /
  Privacy: /privacy
  About: /about
  Archives: /archives
  Music: /music
rss: /atom.xml

# Content
excerpt_link: もっと見る
fancybox: true

# Miscellaneous
google_analytics: UA-46293351-2
favicon: /images/favicon-g.png

toc:
  maxdepth: 3
  class: toc
  slugify: uslug
  decodeEntities: false
  anchor:
    position: after
    symbol: '#'
    style: header-anchor
