# Header
menu:
  Home: /
  About: /about/
  Archives: /archives/
  Music: /music/
  Privacy: /privacy/
rss: /atom.xml

# Content
excerpt_link: もっと見る

# Miscellaneous
google_analytics: 
  tracking_id: UA-46293351-2
  measurement_id: G-J7BH394450
# favicon: /images/favicon-g.png
# apple_touch_icon: /images/apple-touch-icon.png

toc:
  maxdepth: 3
  class: toc
  slugify: uslug
  decodeEntities: false
  anchor:
    position: after
    symbol: '#'
    style: header-anchor
